# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

#私有库
source'https://code.aliyun.com/hengyang.king/MusicHomeSpecs.git'
#公有库
source'https://github.com/CocoaPods/Specs.git' 

target 'Example' do
    pod 'MHPopupView', :path =>'../'


end
